OFILES=xlisp.obj xlbfun.obj xlcont.obj xldbug.obj xldmem.obj xleval.obj \
xlfio.obj xlglob.obj xlimage.obj xlinit.obj xlio.obj xljump.obj xllist.obj \
xlmath.obj xlobj.obj xlpp.obj xlprin.obj xlread.obj xlstr.obj xlstruct.obj \
xlsubr.obj xlsym.obj xlsys.obj msstuff.obj

CFLAGS=/W3 /Gs /Ot /Oi /Ol /Og

.c.obj:
	cl386 -c $(CFLAGS) $<

xlisp.exe:	$(OFILES) xlftab.obj
	link386 /STACK:32767 /PM:NOVIO @xlisp.lnk

xlftab.obj:	xlisp.h osdefs.h osptrs.h
$(OFILES):	xlisp.h
